/// Flutter icons CartIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CartIcons
///      fonts:
///       - asset: fonts/CartIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CartIcons {
  CartIcons._();

  static const _kFontFam = 'CartIcons';

  static const IconData grocery = IconData(0xe800);
  static const IconData account = IconData(0xe808);
  static const IconData bread = IconData(0xe809);
  static const IconData cart = IconData(0xe80a);
  static const IconData favourites = IconData(0xe80b);
  static const IconData home = IconData(0xe80c);
  static const IconData house_hold = IconData(0xe80d);
  static const IconData liquor = IconData(0xe80e);
  static const IconData more = IconData(0xe80f);
}
